users:
  - default
  - name: vmuser
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQJMG8ynRrgMOkTEy/IS7l3Bcc+7LExMynQjZ9QV2CV/fuqGFlCiRT72+aC9bdbfXaWWsqukkSBwfx/uT9vzLd1q1XbW8pNYVErn7VZAAMuxysMullGYFqatTmbwuf8+B2HbfGWcPWCPBRy/fwl1ikesbWGW7szdCiRq2zx2iCPh6q4gPaMwAYSq37E1VfQHDK8LbvbO1zgM2eRIVOZpV7jxgmp4HnEHrs4IvpNyx5gAvORe3mP86FyYuYxyWiZ3633tGdmsdbpFE3ScmDf7cd++Lzc/Z8ycDWTzmDOvThIg9BtnUGWBl75ylmHbtZBQ8r/W5tE3AKERC3DOAMP0jsa2Cn//V2QGyPBtiDzfrM/3gxsO7rSLOh5RhPZJgAeapem+0VxAD2Pyj+6/GmTbGR4uCLNhHySQX9/y9YIgdD57A8FhFo7k6BymuYXnSzrsVs35JNc1ZVPNng0As6nNfarRt57VXJoIwayGN6FWezA77cJdp69HyVegYH6cq+v50= vmuser
